apiVersion: v1
kind: ConfigMap
metadata:
  name: test-motd
data:
  message_1: "Hello, good morning!"
  message_2: "Hello, good evening!"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: optional-workspace-when-
spec:
  serviceAccountName: default
  # workspaces:
  # - name: message-of-the-day
  #   configMap:
  #     name: test-motd
  pipelineSpec:
    workspaces:
    - name: message-of-the-day
      optional: true
      description: |
        If a workspace is provided here then every file at the root of the workspace
        will be printed.
    tasks:
    - name: print-motd
      when:
      - input: "$(workspaces.message-of-the-day.bound)"
        operator: in
        values:
        - "true"
      # workspaces:
      # - name: message-of-the-day
      #   workspace: message-of-the-day
      taskSpec:
        workspaces:
        - name: message-of-the-day
          optional: true
        steps:
        - name: step-1
          image: alpine
          script: |
            #!/usr/bin/env ash
            for f in "$(workspaces.message-of-the-day.path)"/*; do
              cat ${f}
              echo "" #add a new line
            done
    - name: print-default-motd
      when:
      - input: "$(workspaces.message-of-the-day.bound)"
        operator: in
        values:
        - "false"
      taskSpec:
        steps:
        - name: print-default
          image: alpine
          script: |
            echo "No message-of-the-day workspace was provided. This is the default MOTD instead!"
