apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-by-digest-
spec:
  taskSpec:
    steps:
      - image: busybox@sha256:1303dbf110c57f3edf68d9f5a16c082ec06c4cf7604831669faf2c712260b5a0
        args: ['-c', 'echo hello']
