apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: workingdir-
spec:
  taskSpec:
    steps:
    - name: default
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo $PWD
        [[ $PWD == /workspace ]]
    - name: override
      image: ubuntu
      workingDir: '/a/path/to/foo/bar'
      script: |
        #!/usr/bin/env bash
        echo $PWD
        [[ $PWD == /a/path/to/foo/bar ]]
