apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task-results-
spec:
  taskSpec:
    description: |
      A simple task that prints the date.
    results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
    - name: current-date-human-readable
      description: The current date in human readable format
    steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee /tekton/results/current-date-unix-timestamp
    - name: print-date-human-readable
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo $(results.current-date-unix-timestamp.path)
        echo $(results.current-date-human-readable.path)
        ls /tekton/results #tekton creates /tekton/results directory, but the /tekton/results/<files> should be created by tasks
        date | tee $(results.current-date-human-readable.path)
