apiVersion: v1
kind: Secret
metadata:
  name: secret-env-password
stringData:
  ninja: jump
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: secret-as-env-
spec:
  taskSpec:
    steps:
    - name: secret-as-env
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -xe

        [[ $SECRET_PASSWORD == jump ]]
      env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-env-password
            key: ninja
