apiVersion: v1
kind: Secret
metadata:
  name: secret-vol-password
stringData:
  ninja: jump
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: secret-volume-tr-
spec:
  taskSpec:
    steps:
    - name: check-secret
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        SECRET_PASSWORD=$(cat /var/secret/ninja)
        echo ${SECRET_PASSWORD}
        [[ ${SECRET_PASSWORD} == jump ]]
      volumeMounts:
      - name: secret-volume
        mountPath: /var/secret
    volumes:
    - name: secret-volume
      secret:
        secretName: secret-vol-password
