apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
data:
  test.data: run-run-run
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: configmap-in-tr-
spec:
  taskSpec:
    steps:
    - name: use-config-map
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo ${CONFIG_DATA}
        cat /config/test.data

        [[ ${CONFIG_DATA} == $(cat /config/test.data) ]]
      env:
      - name: CONFIG_DATA
        valueFrom:
          configMapKeyRef:
            key: test.data
            name: example-configmap
      volumeMounts:
      - mountPath: /config
        name: config-volume
    volumes:
    - name: config-volume
      configMap:
        name: example-configmap
