apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: pull-request-
spec:
  resources:
    inputs:
    - name: pr
      resourceSpec:
        type: pullRequest
        params:
        - name: url
          value: https://github.com/tektoncd/pipeline/pull/100
  taskSpec:
    resources:
      inputs:
      - name: pr
        type: pullRequest
    steps:
    - name: dump-workspace
      image: ubuntu
      script: |
        find $(resources.inputs.pr.path)/* -type f | xargs tail -n +1
    - name: ensure-approved
      image: ubuntu
      script: |
        if [ -f "$(resources.inputs.pr.path)/labels/approved" ]; then
          echo "PR is approved"
        else
          echo "PR is not approved"
          exit 1
        fi
