apiVersion: v1
kind: Secret
metadata:
  name: secret-vol-param
stringData:
  ninja: stealth
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: secret-name-as-param-
spec:
  taskSpec:
    params:
    - name: SCNAME
      description: Name of seret
      type: string
    steps:
    - name: check-password
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        SECRET_PASSWORD=$(cat /var/secret/ninja)
        echo $SECRET_PASSWORD
        [[ $SECRET_PASSWORD == stealth ]]
      volumeMounts:
      - name: secret-volume
        mountPath: /var/secret
    volumes:
    - name: secret-volume
      secret:
        secretName: "$(params.SCNAME)"
  params:
  - name: SCNAME
    value: secret-vol-param
