apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-testing-volume-args
data:
  test.data: tasks are my jam
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task-volume-args-
spec:
  taskSpec:
    params:
    - name: CFGNAME
      type: string
      description: Name of config map
    steps:
    - name: ready
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        cat /configmap/test.data
      volumeMounts:
      - name: configmap
        mountpath: /configmap
    volumes:
    - name: configmap
      configMap:
        name: $(params.CFGNAME)
  params:
  - name: CFGNAME
    value: config-for-testing-volume-args
