apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task-1
spec:
  params:
  - name: param-1
  - name: param-2
  steps:
  - name: step-1
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo param1: $(params.param-1)
      echo param1: $(inputs.params.param-1)
      echo param2: $(params.param-2)
      echo param2: $(inputs.params.param-2)
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: test-tr-1
spec:
  params:
  - name: param-1
    value: "abcd"
  - name: param-2
    value: "xyz"
  taskRef:
    name: test-task-1